components/dns/provider.tf

Enable backend for dns

---

apps.yaml

Add outh2 perms for sbox jenkins

---

apps.yaml

Enable groupMembershipClaims 

---

apps.yaml

Add sandbox jenkins static url

---

apps.yaml

Fix read perms

---

components/app-proxy/vm.tf
environments/variables.tf

https://tools.hmcts.net/jira/browse/DTSPO-14603
Tagging Auto Shutdown for App Proxy
```
[ ] Yes
[x] No
```

DTSPO-14603: Tagging Auto Shutdown for App Proxy

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-14754
Add sds sonarqube apps in sbox and ptl

DTSPO-14754 - Add sds sonarqube webhook

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-14754
Add cft ptl jenkins sonarqube webhook

DTSPO-14754 - Add cft sonarqube webhook

---

apps.yaml

[DTSPO-15318](https://tools.hmcts.net/jira/browse/DTSPO-15318)
Adds SDS ptl jenkins to app proxy

DTSPO-15318: Add SDS Jenkins PTL to app proxy

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-15318
Add config for static ptl jenkins in sds

DTSPO-15318: Add SDS jenkins static

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-15318
This change:
- Adds config for ptl jenkins and static ptl jenkins to app-proxy

DTSPO-15318: Add CFT Jenkins PTL config to app-proxy

---

README.md

New app registrations implementing MS graph permissions are pending admin consent being granted in Azure, after making a new app you need to contact a GA to approve this

Update to reference graph permissions issue

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-15319
* Update internalUrl for netbox sandbox

Netbox Sandbox: fix internalUrl

---

apps.yaml

Reverts hmcts/azure-app-proxy#30

Revert "Netbox Sandbox: fix internalUrl"

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-15319
* Update internal url for PTL netbox

Update internal url for PTL netbox

---

apps.yaml

FIX: added missing internal URL

fix: added missing internal URL

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-15627
Removing Nessus to fresh start to try and solve error here
https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=488286&view=logs&j=9db58e76-1d26-5f76-d614-1ee16dc9c71f&t=997c4fa3-8d1b-5299-68a7-4c1a539fbb17

removing nessus for fresh start

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-15627

reverted last deletion

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-15627
Correcting internal url for the Nessus application

changing Nessus app internal URL

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-15778
Adds config for backstage
Following this PR:
- Private DNS for backstage new record to point to traefik
- Change ingress in traefik
- Update old DNS records to point to FD
- Add FD redirect to new URL

DTSPO-15778: Add config for backstage

---

apps.yaml

Remove backstage passthrough auth

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-15778
Updates redirects to get this fully working (testing by manually changing and i can now login to backstage fine , so adding as code)

DTSPO-15778: Update redirect uris backstage

---

components/app-proxy/Bootstrap-Application-Proxy.ps1
components/app-proxy/vm.tf

https://tools.hmcts.net/jira/browse/DTSPO-17511
changing testpath and increasing timeout

changing testpath and increasing timeout

---

components/app-proxy/Bootstrap-Application-Proxy.ps1

Module name has changed and needs to be updated

Update module name

---

.gitignore
README.md
azure-pipelines.yaml

https://tools.hmcts.net/jira/browse/DTSPO-17511
Targeting app-proxy-1 for pipeline run

Targeting app-proxy-1

---

azure-pipelines.yaml
components/app-proxy/Bootstrap-Application-Proxy.ps1

https://tools.hmcts.net/jira/browse/DTSPO-17682
Adding minor update to script

Adding minor update to script

---

azure-pipelines.yaml

https://tools.hmcts.net/jira/browse/DTSPO-17511
Cleaning up temp fix

Cleaning up temp fix

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-17544
Add incident api slack endpoint
This is to allow slack to connect to the app so slash commands and events work from within Slack

DTSPO-17544 - Add incident api slack endpoint

---

apps.yaml

https://tools.hmcts.net/jira/browse/DTSPO-18210
Add test app for slack incident bot
This is so I can test it from slack to make sure all aspects are working before pushing out to live
Will be deleted once completed

DTSPO-18210 - Add test endpoint

---

apps.yaml

Reverts hmcts/azure-app-proxy#65
Testing has completed

Revert "DTSPO-18210 - Add test endpoint"

---

apps.yaml

DTSPO-18399
setup app proxy for incident bot sandbox

DTSPO-18399 - setup app proxy for incident bot sandbox

---

apps.yaml

[DTSPO-18399](https://tools.hmcts.net/jira/browse/DTSPO-18399)
Adding another url for the sandbox incident bot.

DTSPO-18399 additional config for sandbox incident bot

---

apps.yaml

[### Jira link](https://tools.hmcts.net/jira/browse/DTSPO-18624)

Updating App Proxy to use the same cert as the VPN (Sandbox)

---

apps.yaml

Tested successfully on Sandbox

Updating App Proxy to use the same cert as the VPN (Prod)

---

components/app-proxy/Bootstrap-Application-Proxy.ps1

- CustomScript extension failing to provision due to an error when running `az login`
- Have updated the script to clear accounts and set `core.enable_broker_on_windows` to false prior to login
Tested this manually on `app-proxy-0`.
Before:
After:

Fix az login in bootstrap script

---

components/app-proxy/Bootstrap-Application-Proxy.ps1

- Increasing timeout in script and adding additional logging to troubleshoot timeout `Time out has expired and the operation has not been completed.`

Update bootstrap script with more logging and increased timeout

---

components/app-proxy/Bootstrap-Application-Proxy.ps1

- Reverts changes to script in previous commit - https://github.com/hmcts/azure-app-proxy/pull/75
- Tested the script manually on `app-proxy-0` and it worked so issue must be elsewhere

Revert script update

---

components/app-proxy/provider.tf
components/app-proxy/vm.tf

https://tools.hmcts.net/jira/browse/DTSPO-18845
- Re-adding the AMA agent to app proxy VMs

Re-add ama agent

---

components/app-proxy/vm.tf

- Sets `systemassigned_identity` to `true` on the app proxy VMs. This is required for the AMA to work.

Enable systemassigned_identity on VMs

---

components/dns/provider.tf

Update DNS component azurerm provider version to fix MS timeinsights bug

Update DNS component azurerm provider version to fix MS timeinsights bug

---

components/app-proxy/Bootstrap-Application-Proxy.ps1

Corrected script after testing..

DTSPO-18960 - updated the script

---

README.md

See [DTSPO-18960](https://tools.hmcts.net/jira/browse/DTSPO-18960)
Update readme with details of the service that needs to be running and details about the new scheduled task to monitor the service

DTSPO-18960 - Update README.md

---

components/app-proxy/provider.tf

https://tools.hmcts.net/jira/browse/DTSPO-22520
Updating terraform azurerm provider version
Pipeline plan run

Updating Provider Version for Compatiblity with New Updates to Module

---

apps.yaml

N/A
dcd_team_secops_v2 no longer exists, dcd_team_secops_sc_v2 seems like a reasonable replacement.

fix: dcd_team_secops_v2 -> dcd_team_secops_sc_v2

---

components/app-proxy/vm.tf

https://tools.hmcts.net/jira/browse/DTSPO-24125
- Reverting to master branch of module after merging changes

Revert to master branch

---

apps.yaml

Dtspo-26286
correct rediretUrl for Neuvector

Dtspo 26286 defined redirect urls neuvector

---

apps.yaml

DTSPO-26286
define `identifierUrls` and `preferredSingleSignOnMode` for Neuvector apps in AAT

define identifierUrls and preferredSingleSignOnMode for Neuvector apps 

---

apps.yaml

DTSPO-28268 
add more redirectUrls (i.e. ACS urls) for neuvector in AAT

add more redirectUrls (i.e. ACS urls) for neuvector in AAT

---

apps.yaml

DTSPO-26286
redirectUrls need to match  identifierUrls for neuvector in AAT

match redirectUrls to identifierUrls for neuvector in AAT

---

apps.yaml

Testing Neuvector with http internal URL

Testing Neuvector with http internal URL

---

apps.yaml

Testing original Neuvector internal URL 01

Testing original Neuvector internal URL 01

---

apps.yaml

DTSPO-26286
remove internal identifier urls and reply urls

remove internal identifier urls and reply urls AAT

---

apps.yaml

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
register neuvector non prods e.g. ithc, perftest, prod, and ptl

Dtspo 26286 register neuvector non-prod clusters

---

apps.yaml

remove cft neuvector - ptl 00

---

apps.yaml

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

WM-300 cactus app proxy fix

---

apps.yaml

N/A
Switch Cactus app proxy config to use *.apps.hmcts.net cert rather than TLD cert.

feat: switch to *.apps.hmcts.net cert

---

apps.yaml

N/A
Use wildcard certs specific for staging/dev. App Proxy needs the cert to be issued for the specific intermediate domain, not just a wildcard for the TLD.

fix: use correct certs for the subdomain
